version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_cont
    ports:
      - "80:80"
    depends_on:
      - django  
    restart: always 
    networks:
      - notesapp

  django: 
    build:
      context: .
    
    container_name: django_cont  
    env_file:
      - ".env"
    networks:
      - notesapp  
    depends_on:
      - mysql 
    ports:
      - "8000:8000"  
    restart: always  
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"  
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
        
  mysql:
    image: mysql
    container_name: mysql_cont
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - notesapp
    volumes:
      - ./mysql-data:/var/lib/mysql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  notesapp:
    driver: bridge
